version: 1
name: calculator
description: This problem is for the tutorial
tags:
  - tutorial
  - cli
category: example
difficulty: Easy
entry_file: calculator
timeout: 10

checkpoints:
  checkpoint_1:
    version: 1
    order: 1
    state: Core Tests
    timeout: 30

  checkpoint_2:
    version: 1
    order: 2
    state: Core Tests
    timeout: 30

  checkpoint_3:
    version: 1
    order: 3
    state: Core Tests
    timeout: 30

markers:
  functionality: "non-core / nice-to-have tests"
  error: "error-handling / edge-case tests"
