case:
  arguments: --output output.csv --key id data.csv
  input_files:
  - content:
    - city: Tokyo
      id: '1'
      name: "\u7530\u4E2D\u592A\u90CE"
    - city: "S\xE3o Paulo"
      id: '2'
      name: "Jos\xE9 Silva"
    - city: Moscow
      id: '3'
      name: "\u0418\u0432\u0430\u043D \u041F\u0435\u0442\u0440\u043E\u0432"
    - city: Beijing
      id: '4'
      name: "\u674E\u660E"
    - city: Berlin
      id: '5'
      name: "M\xFCller"
    file_type: csv
    path: data.csv
expected:
  files:
    output.csv:
    - city: Tokyo
      id: 1
      name: "\u7530\u4E2D\u592A\u90CE"
    - city: "S\xE3o Paulo"
      id: 2
      name: "Jos\xE9 Silva"
    - city: Moscow
      id: 3
      name: "\u0418\u0432\u0430\u043D \u041F\u0435\u0442\u0440\u043E\u0432"
    - city: Beijing
      id: 4
      name: "\u674E\u660E"
    - city: Berlin
      id: 5
      name: "M\xFCller"
  status_code: 0
