loader:
  type: files # This case is laid out as each sub directory is a case
  pattern: "*.yaml" # The base pattern to find directories 
  # How to process the files found. Those not listed here are assumed to just
  # be input files and are copied over raw.
  rules: 
    # We are looking for just single files with different names, so that means
    # we need to map the single file to the stdin field of the case
    __SINGLE__: 
      # We are mapping the single file to the root of the case, meaning that
      # the single file is essentially a meta file.
      dest: "__root__"  
      loader: yaml # We are using yaml to load the file

# How we will determine if the submission is correct
verifiers: 
  had_error: # Checks that the status code is exact match 0
    type: status_code
    value: null # Do NOT use a static value here, rather use the case expected value

constants:
  arguments: ["--eval"]

# We dont care about normalizing the result, because we are just checking if the submission had an error
normalizers: []
expected_normalizers: []