case:
  headers:
    content-type: application/json; charset=utf-8
  id: search_tool_name_with_environment
  method: GET
  path: /trajectories?tool_name=search_wiki&environment=local-sim
expected:
  output:
    properties:
      items:
        type: array
        minItems: 1
        items:
          properties:
            environment:
              const: local-sim
          required:
            - environment
          type: object
      next_cursor:
        type: [string, "null"]
    required:
      - items
      - next_cursor
    type: object
  status_code: 200
