internal_name: gemini-2.5-pro
provider: google
provider_slugs:
  openrouter: google/gemini-2.5-pro
pricing:
  input: 1.25
  output: 10
  cache_read: 0.31
  cache_write: 0
aliases:
  - gemini-2.5-pro-preview-05-06

