version: 1
name: yaml_joiner
description: A simple yaml problem to demonstrate static files/group files
tags:
  - tutorial
  - cli
category: example
difficulty: Easy
entry_file: solution
timeout: 10

static_assets:
  cfg_dir:
    path: static_cfgs

checkpoints:
  checkpoint_1:
    version: 1
    order: 1
    state: Core Tests
    timeout: 10

  checkpoint_2:
    version: 1
    order: 2
    state: Core Tests
    timeout: 10

markers:
  functionality: "non-core / nice-to-have tests"
  error: "error-handling / edge-case tests"
