version: 1
timeout: 10
specification: spec.md
group_files: []
state: Core Tests
groups:
  random:
    group_files:
      - dummy/ignore.yaml
    type: Core
  c1_core:
    group_files:
      - dummy/ignore.yaml
    type: Regression
    original_checkpoint: checkpoint_1
    original_group: core